<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>test_ddt_multi_REG_suites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d18ed9a5-0c65-4e7a-b048-36994341cf37</testSuiteGuid>
   <testCaseLink>
      <guid>f1bd9bd1-5cc3-4e78-abe9-cfcfddaf66a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UAT_LOGIN_Registration/new_registration18.3.24</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>96632735-5692-44cc-afd3-f64cb4b76151</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT_registration_testing_multiple_user/Test_Data_multiple_REG</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f548170e-2af6-4929-b1b1-3806ee4d5d36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cdcc839-70c1-4b6f-81e5-466f3aaa0f61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89ef912c-80c9-4103-a7f1-1bd20a56fe47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e02e269-0bcc-4ab7-918f-52acb94cb465</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>993617a0-86cd-4ba0-86d3-fda190f6b1fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db6c06ac-7361-4e99-ace4-171423f07b73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b921196f-1fa9-4f34-8bbd-45f053575033</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
